Implemented a very simple language switcher;
WouterRBerkhout/FRONT-VVE-app-ipsen5 pull request #5
Opened 2022-05-11 19:56 UTC by cyanthvibes

Default language is Dutch, and user preference is stored in localStorage.

Large amount of file changes due to optimising imports and forcing ESlint rules across the whole project.

2022-05-11 22:03 UTC, WouterRBerkhout requested changes
Please keep resident and manager modules seperate

2022-05-11 22:03 UTC, WouterRBerkhout commented on src/app/resident/resident.module.ts
> +    ManagerModule,
Why are you importing the manager module into the resident module? Seems counter intuitive

2022-05-11 22:15 UTC, WouterRBerkhout commented on src/app/resident/resident.module.ts
> +    ManagerModule,
Will merge for demo purposes, but will change later

2022-05-11 22:15 UTC, WouterRBerkhout approved these changes

2022-05-11 22:16 UTC, merged

2022-05-12 00:09 UTC, cyanthvibes commented on src/app/resident/resident.module.ts
> +    ManagerModule,
Might've been a result of my own testing and therefore clowncode. Will alter this in a future commit when styling has been properly done for the language switcher ;)